### ISSUE TITLE
Add Mailfence to the list of suggested products

### ISSUE THREAD

**Issue by resto1231** [wgx/ethicalhq-firefox#3]
Hello WIll,

Your colleague Radu contacted us (Mailfence) via Twitter for your extension. It's a really cool extension to have as a little companion i was wondering whether you would be willing to add Mailfence?

Thanks a lot 

Orestis with Mailfence.

**Comment by wgx** [comment]
Hey Orestis - please open a pull request on the CSV to add your product in.

**Comment by resto1231** [comment]
Done.
